### ISSUE TITLE
电话录音对话，啥也没有输出，咋回事呢

### ISSUE THREAD

**Issue by njhouse365** [revdotcom/reverb#15]
python3 wenet/bin/recognize_wav.py \
	--config  /home/house365ai/xxm/reverb/asr/model/config.yaml \
    --checkpoint /home/house365ai/xxm/reverb/asr/model/reverb_asr_v1.pt \
    --audio /home/house365ai/xxm/reverb/asr/data/07.wav \
    --modes ctc_prefix_beam_search attention_rescoring \
    --gpu 7 \
    --verbatimicity 1.0 \
	--result_dir /home/house365ai/xxm/reverb/asr/result

**Comment by jprobichaud** [comment]
Is it possible for you to share the audio file ?

**Comment by njhouse365** [comment]
[07.zip](https://github.com/user-attachments/files/17323041/07.zip)

**Comment by njhouse365** [comment]
phone record

**Comment by jprobichaud** [comment]
Thanks.  Your file is stereo and encoded with some, something that the current code doesn't handle explicitly. As such, the features extracted are quite different than what converting the audio to mono would do.

That being said, the audio doesn't contain English speech and for that reason, even when I downmix to mono and process the file, what I get is just a series of <unknown> tokens.  This model can only handle English for now.

**Comment by njhouse365** [comment]
oh，thanks
