### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [revdotcom/reverb#9]
Hi,
Thanks for releasing Reverb!
I noticed that the README file describes this repo as an open source framework for inference/evaluation. It looks like the license is not an OSI-approved OSD license.
Are there any plans to switch the license to an [open source](https://opensource.org/osd) license?
Thanks!

**Comment by pique0822** [comment]
Hi there, 

Thanks for checking out Reverb and for pointing out our license issue --- we just updated our code's license to Apache2 to facilitate it's use for inference/evaluation! We did however keep the original license for the models themselves which can be seen when downloading them from HuggingFace.

Thanks again!
